### ISSUE TITLE
How to increase performance?

### ISSUE THREAD

**Issue by Lucgarg** [crobox/clickhouse-scala-client#124]
Hello, i am using the clickhouse-client for consumer from apache pulsar. 
i think i'm doing something wrong. I configure the application.cong and overwrite the indexer options, but the batching it doesn't seem to work since the values ​​are inserted in clickhouse of in batches of 50 rows.

now i'm using the next code 

  sink.runWith(Source.single(Insert("prueba.con", new String(msg.getData))))

what I hope is that messages accumulate until the batch or flush interval is fulfilled

**Comment by lwolters** [comment]
Hi Lurgarg.

Your assumption is right. Either the messages accumulate until the batch size is met, or whenever the flush interval is reached; whatever comes first.

Could you double check the following settings:

crobox.clickhouse.indexer {
    # maximum number of items to buffer before doing an insert
    batch-size = 10000
    # number of max insert operations on each individual table
    concurrent-requests = 1
    # maximum time to buffer the data before doing an insert
    flush-interval = 5 seconds
  }

You can always put these settings in an file named 'application.conf' and make sure this file is located in your classpath

**Comment by Lucgarg** [comment]
Thank you very much for such a quick response.

After debugging I have verified that the configurations are overwritten. I have also tried to change the type of engine in clickhouse, inserting the message directly in a table with engine mergetree and another using the engine buffer linking with the table of mergetree. But in the engine buffer the performance is the same.

all my code is this 

  **val config: Config = ConfigFactory.load()

  val client: ClickhouseClient = new ClickhouseClient(Some(config));

  implicit val ec: scala.concurrent.ExecutionContext = scala.concurrent.ExecutionContext.global

  val sink = ClickhouseSink.insertSink(config, client, Some("imp"))

  implicit val system: ActorSystem = ActorSystem("nombre")


    def writeToClick(msg:Message[Array[Byte]]): Unit ={
 

        sink.runWith(Source.single(Insert("prueba.con", new String(msg.getData))))


    }**


and the method is call in a java class in a loop.

**Comment by juliito19** [comment]
Hiii Lucas I think that a solution can be to start a Cluster for you service

**Comment by lwolters** [comment]
HI Lucgarg.

Looks like you switched the sink and the source. See https://doc.akka.io/docs/akka/current/stream/operators/Source/queue.html

A gist of something that might work better:

val source = Source((1 to 2000).map(i => Insert("<table_name>", "Entity as JSON")))
val sink = ClickhouseSink.insertSink(config, client, Some("imp"))
source.runWith(clickhousesink)

**Comment by Lucgarg** [comment]
Thank you very much and sorry for the inconvenience. now it works great and now I can start looking from here.
