### ISSUE TITLE
 Get the message failing

### ISSUE THREAD

**Issue by Lucgarg** [crobox/clickhouse-scala-client#125]
Hello, is there a possibility to retrieve the failed message? 

Now, i am using  recoverWith and I get it to send me the error message with the messages that have failed in a string, but it is not useful to me to retrieve the message. 

I am thinking in send  id of message in de Insert block, and then put this how x-ClickHouse-Query-Id, and recover and then send it again as an error in case the message is not sent
this is the code: 

  Await.result(source.runWith(sink).recoverWith{
      case ex :RuntimeException => Future.successful(println(ex.getCause))
    }, 10.seconds)

Exist a best posibility for get the message what fails?

**Comment by juliito19** [comment]
Yeah Lucas , you are Right, you can see more Information in #123

**Comment by lwolters** [comment]
Hi Lucgarg,

Your solution should work; although many others are valid too. 

BTW: Did you consider using a logging framework, i.e. log4j that logs the message & cause. Right now you're only printing the stacktrace / cause. Did you also tried: println(ex.getMessage()) ?

**Comment by Lucgarg** [comment]
Thank for the answer. Yes a probe with all options for print de error message but nothing. 

After inquiring into the documentation in the community forums if I am not mistaken, when making a batch in clickhouse it does not return exactly the row that has failed you. 

https://github.com/ClickHouse/ClickHouse/issues/7522
