### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by constantijn** [crobox/clickhouse-scala-client#140]
Hi,

I was wondering how I configure the client to use https instead of http?
It's needed to communicate with the new ClickHouse cloud offering, which means my requests go over the open internet.

I don't see any options for it in the config.

**Comment by sjoerdmulder** [comment]
Hi @constantijn,

Sorry for the late reply; something is going on with Github not sending notifications.

This should already be possible if you include 'protocol in the host property e.g. `host = 'https://clickhouse-cloud`

See: https://github.com/crobox/clickhouse-scala-client/blob/master/client/src/main/scala/com.crobox.clickhouse/internal/ClickhouseHostBuilder.scala#L8
