### ISSUE TITLE
Release Scala 3 artefact

### ISSUE THREAD

**Issue by lpawlak1** [crobox/clickhouse-scala-client#160]
Hi team, 

I've seen that scala 3 support was merged 2 months ago, but publish was skipped. 

Is there any reason for that? 
When do you plan to release client with Scala 3 support? 

Thanks

**Comment by lwolters** [comment]
Hi Lukasz,

I've just released version 1.2.0 which has full scala 3 support!

Take care,

Leonard

Leonard Wolters
+31 (0)6 555 304 01
***@***.***

**Comment by lpawlak1** [comment]
Hi,

Thanks so much!!!

Take care, 
Łukasz
