### ISSUE TITLE
Proper support for insert statement

### ISSUE THREAD

**Issue by rbrondgeest** [crobox/clickhouse-scala-client#19]
ClickhouseQueryExecutor offers "def insert", 
but we currently do not support insert statements in the DSL. 
Should not be to much work to build, and probably form a solid use-case for many users of the DSL.

**Comment by ecyshor** [comment]
We expose a sink which accepts an `Insert` with the json and table.
This should be expanded to add support for other formats which are supported by akka

**Comment by rbrondgeest** [comment]
Would be nice to allow for insert into (select from) statements to be defined in the DSL as-well.
