### ISSUE TITLE
can u show me more usage examples?

### ISSUE THREAD

**Issue by Tasselmi** [crobox/clickhouse-scala-client#74]
I import your jar package in my project.
BUT how can I use your project? IT makes me confused.
Firstly I think it is something like jdbc driver , but it turns out I am wrong.

**Comment by sjoerdmulder** [comment]
It's not a jdbc driver at all. It's a non-blocking async scala driver.

This usage example should work: https://github.com/crobox/clickhouse-scala-client#client
Make sure you set the right configuration (using Typesafe Config) https://github.com/crobox/clickhouse-scala-client#connection-configuration

What are the specific use-cases you are looking for? Always happy to improve the documentation.

**Comment by Tasselmi** [comment]
> It's not a jdbc driver at all. It's a non-blocking async scala driver.
> 
> This usage example should work: https://github.com/crobox/clickhouse-scala-client#client
> Make sure you set the right configuration (using Typesafe Config) https://github.com/crobox/clickhouse-scala-client#connection-configuration
> 
> What are the specific use-cases you are looking for? Always happy to improve the documentation.

thank you for your reply.  
actually I want to know how to use and modify config. 
`val client = new ClickhouseClient(config, queryDatabase)`
How can I modify the config parameters ?
I see you point out that it resides in `reference.conf`,  but it is a file that can't be modified when I insert  
your project as a jar package into my project . How can I modify the file or set the parameters by code?

Thanks.

**Comment by sjoerdmulder** [comment]
Ah yes, you can use your own `application.conf` for this. Look at Typesafe Config: https://github.com/lightbend/config how this all works and get a configured `val config: Config`

**Comment by Tasselmi** [comment]
> Ah yes, you can use your own `application.conf` for this. Look at Typesafe Config: https://github.com/lightbend/config how this all works and get a configured `val config: Config`

Thanks. you help me a lot.
