### ISSUE TITLE
can you help me run my app

### ISSUE THREAD

**Issue by Tasselmi** [crobox/clickhouse-scala-client#76]
Even now I still can not make my app running~~
Can you show me a little paragraph of code  or a tiny app ?
I am new in scala.  I am a pythoner before......

help me.  Thanks.

<img width="1166" alt="2018-11-14 9 47 33" src="https://user-images.githubusercontent.com/12438278/48454562-9dc78280-e7f2-11e8-8265-066285210588.png">

**Comment by sjoerdmulder** [comment]
The issues section are meant for bugs in our project and not for questions on howto learn Scala. I can highly recommend the following as starter course: https://www.coursera.org/learn/progfun1 if you want to get more familiar with Scala.

Please only open issues that are actual bugs or issues related with this project and not about your own code that is missing implicits in scope or a non initialized variables.

Thank you!
