### ISSUE TITLE
Insert sink stops working after one bad insert

### ISSUE THREAD

**Issue by DrStep** [crobox/clickhouse-scala-client#89]
Hi, guys, thanks for this lib, it's very useful.

Meet some issues:
1) Use case: we send one invalid message to CH and insertions fail. Then we try to insert valid message in CH.
What I expect: insertion of first message failed and valid message inserted successfully.
What I get: after first failed insert insertion pipeline stop working and we can not load data (even valid) from that moment

The reason for it is in com.crobox.clickhouse.stream.ClickhouseSink in method insertSink:
https://github.com/crobox/clickhouse-scala-client/blob/9e386719ac3aa3f71c6f4844aafc48cf13da41fd/client/src/main/scala/com.crobox.clickhouse/stream/ClickhouseSink.scala#L42

If in recover block we will return _Seq.empty_, everything will work fine and after one bad insert will not break whole pipeline.

2) It would be nice to have an opportunity to pass to insertSink function for processing bad inserts, that would be called in recover section (in the code section above). It would be usefull, for example, for custom logging

Second issue is an optional feature, but first one is a big problem, imho.

Thanks :)

**Comment by sjoerdmulder** [comment]
Thanks! Appreciate the feedback.

The issue 1 you describe is actually a feature that can also solve nr 2 :smile: 
The reason a custom `ClickhouseIndexingException` is throw is so that you then can recover from it using your own logic and possible handle bad inserts using stream error handling; see: https://doc.akka.io/docs/akka/current/stream/stream-error.html#supervision-strategies

f.e. we implemented a strategy that looks something like:
```
 ActorAttributes.supervisionStrategy({
   case ex: ClickhouseIndexingException =>
    ...
    some logic that handles the exception f.e. by storing the `ex.payload` in another way
    ...
    Supervision.Resume // This resumes the stream and doesn't stop it
  case other => 
    Supervision.Stop // Something is really broken; abort!
})
```

**Comment by DrStep** [comment]
@sjoerdmulder wow, amazing, so this is my fault due to not much experience with Akka Streams errors handling 😅
Thanks a lot!
