### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by zella** [crobox/clickhouse-scala-client#94]
Any plans about it?

**Comment by sjoerdmulder** [comment]
Yes! But for now it has low priority. If you want to create a PR that would great!

**Comment by sjoerdmulder** [comment]
I remember again, i tried it a couple of months back but i got stuck because of a dependency not being available for 2.13... See: https://github.com/Atry/fastring/issues/30

**Comment by sjoerdmulder** [comment]
I removed fastring and tried to compile with 2.13 but there are some deeper issues with the test... if you could pick it up / continue that would be great! :+1:

**Comment by sjoerdmulder** [comment]
Okay! release 0.9.2 is done with support for scala 2.13 :)
